spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/perfume-shop-app-db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${MY_SQL_USER:root}
    password: ${MY_SQL_PASSWORD:12345}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    blog: WARN
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor: WARN
      nodeValue: WARN
#server:
#  port: 8087
#mail:
#  host: "localhost"
#  port: 1025
#  username: ""
#  password: ""
perfumeshop:
  remember.me.key: ${REMEMBER_ME_KEY}
  default.admin.pass: ${DEFAULT_ADMIN_PASS}
  default.admin.phone: ${DEFAULT_ADMIN_PHONE}
cloudinary:
  api.key: "463111485397821"
  cloud.name: "dvj9qondf"
  api.secret: ${CLOUDINARY_API_SECRET}